// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: todos.sql

package db

import (
	"context"
)

const createTodo = `-- name: CreateTodo :one
INSERT INTO todos (
	title,
	description,
	completed,
	created_at,
	updated_at
) VALUES (
	$1,
	$2,
	$3,
	NOW(),
	NOW()
)
RETURNING id, title, description, completed, created_at, updated_at
`

type CreateTodoParams struct {
	Title       string  `json:"title"`
	Description *string `json:"description"`
	Completed   bool    `json:"completed"`
}

func (q *Queries) CreateTodo(ctx context.Context, arg CreateTodoParams) (Todo, error) {
	row := q.db.QueryRow(ctx, createTodo, arg.Title, arg.Description, arg.Completed)
	var i Todo
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.Completed,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteTodo = `-- name: DeleteTodo :execrows
DELETE FROM todos
WHERE id = $1
`

func (q *Queries) DeleteTodo(ctx context.Context, id int64) (int64, error) {
	result, err := q.db.Exec(ctx, deleteTodo, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getTodo = `-- name: GetTodo :one
SELECT id, title, description, completed, created_at, updated_at
FROM todos
WHERE id = $1
`

func (q *Queries) GetTodo(ctx context.Context, id int64) (Todo, error) {
	row := q.db.QueryRow(ctx, getTodo, id)
	var i Todo
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.Completed,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listTodos = `-- name: ListTodos :many
SELECT id, title, description, completed, created_at, updated_at
FROM todos
ORDER BY id
`

func (q *Queries) ListTodos(ctx context.Context) ([]Todo, error) {
	rows, err := q.db.Query(ctx, listTodos)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Todo
	for rows.Next() {
		var i Todo
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Description,
			&i.Completed,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const replaceTodo = `-- name: ReplaceTodo :one
UPDATE todos
SET
	title = $1,
	description = $2,
	completed = $3,
	updated_at = NOW()
WHERE id = $4
RETURNING id, title, description, completed, created_at, updated_at
`

type ReplaceTodoParams struct {
	Title       string  `json:"title"`
	Description *string `json:"description"`
	Completed   bool    `json:"completed"`
	ID          int64   `json:"id"`
}

func (q *Queries) ReplaceTodo(ctx context.Context, arg ReplaceTodoParams) (Todo, error) {
	row := q.db.QueryRow(ctx, replaceTodo,
		arg.Title,
		arg.Description,
		arg.Completed,
		arg.ID,
	)
	var i Todo
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.Completed,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateTodo = `-- name: UpdateTodo :one
UPDATE todos
SET
	title = COALESCE($1, title),
	description = CASE WHEN $2::bool THEN $3 ELSE description END,
	completed = COALESCE($4, completed),
	updated_at = NOW()
WHERE id = $5
RETURNING id, title, description, completed, created_at, updated_at
`

type UpdateTodoParams struct {
	Title          *string `json:"title"`
	DescriptionSet bool    `json:"description_set"`
	Description    *string `json:"description"`
	Completed      *bool   `json:"completed"`
	ID             int64   `json:"id"`
}

func (q *Queries) UpdateTodo(ctx context.Context, arg UpdateTodoParams) (Todo, error) {
	row := q.db.QueryRow(ctx, updateTodo,
		arg.Title,
		arg.DescriptionSet,
		arg.Description,
		arg.Completed,
		arg.ID,
	)
	var i Todo
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.Completed,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
